name: deploy pages

on:
  workflow_dispatch:
  push:
    tags:
      - "**"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version-file: ".node-version"
          cache: "yarn"
      - name: build
        run: |
          yarn install --frozen-lockfile
          yarn build
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
